### ISSUE TITLE
1.12 - Mod crashes without Tinkers Construct installed

### ISSUE THREAD

**Issue by MattJohns** [SlimeKnights/HarvestTweaks#20]
Testing without Tinkers Construct, just the mod (and the associated library).  Set stone to harvest level 3.  As soon as you swing at stone it crashes with:

```
[22:21:33] [main/ERROR]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerEvent$BreakSpeed@1b5fda33:
java.lang.NoClassDefFoundError: slimeknights/tconstruct/library/utils/ToolHelper
	at slimeknights.harvesttweaks.ExtraHarvestLevelHandler.breakSpeed(ExtraHarvestLevelHandler.java:46) ~[ExtraHarvestLevelHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_47_ExtraHarvestLevelHandler_breakSpeed_BreakSpeed.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.getBreakSpeed(ForgeEventFactory.java:170) [ForgeEventFactory.class:?]
	at net.minecraft.entity.player.EntityPlayer.getDigSpeed(EntityPlayer.java:836) [aed.class:?]
	at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:232) [ForgeHooks.class:?]
	at net.minecraft.block.Block.func_180647_a(Block.java:559) [aow.class:?]
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185903_a(BlockStateContainer.java:408) [awu$a.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:246) [bsa.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180512_c(PlayerControllerMP.java:334) [bsa.class:?]
	at net.minecraft.client.Minecraft.func_147115_a(Minecraft.java:1478) [bib.class:?]
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2266) [bib.class:?]
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1806) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ClassNotFoundException: slimeknights.tconstruct.library.utils.ToolHelper
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	... 24 more
Caused by: java.lang.NullPointerException
```

**Comment by bonii-xx** [comment]
Oh my, looks like something loads that shouldn't load. I don't know when I'll have time to take a look.

**Comment by Sixdd6** [comment]
Having the same issue here, would be great if a fix gets put out soon, till then I have to remove this from my server. :(

**Comment by The-Arcanian** [comment]
I am getting it when hitting stone with a stone axe, but not a stone pickaxe. Also going to have to remove this until it is fixed.

**Comment by pixzi** [comment]
i got the same issue, just by punching with my hand. Strange as the only thing i changed was the ability to not much wood.

**Comment by PickyPixelStudio** [comment]
Hey!

Two years later, no fix for this problem... =/

**Comment by bonii-xx** [comment]
Oh, yeah. I forgot about this. I don't really have the time to keep this updated, sorry.
