### ISSUE TITLE
Crash when Tool Level Too Low

### ISSUE THREAD

**Issue by pap1723** [SlimeKnights/HarvestTweaks#25]
I don't have a ton of details (I really do apologize for this), but on a 1.12.2 fresh install, I tested a HarvestTweaks config to see if I could add levels to my tools. I wanted to extend the levels to 5. 

I set the Iron pickaxe as a Level 1 and the Diamond Pickaxe as a Level 5. I set stone to be a Level 1 block and Sandstone to be a Level 5 block.

I could mine the Stone no problem with the Iron Pick, and I could mine the Sandstone and Stone no problem with the Diamond Pick. When I tried to mine the Sandstone (Level 5) with the Iron Pick (Level 1), it immediately crashed.

`---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 3/9/18 8:48 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: slimeknights/tconstruct/library/utils/ToolHelper
	at slimeknights.harvesttweaks.ExtraHarvestLevelHandler.breakSpeed(ExtraHarvestLevelHandler.java:46)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_41_ExtraHarvestLevelHandler_breakSpeed_BreakSpeed.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.event.ForgeEventFactory.getBreakSpeed(ForgeEventFactory.java:171)
	at net.minecraft.entity.player.EntityPlayer.getDigSpeed(EntityPlayer.java:836)
	at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:234)
	at net.minecraft.block.Block.func_180647_a(Block.java:559)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185903_a(BlockStateContainer.java:408)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:246)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1516)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2247)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1806)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: slimeknights.tconstruct.library.utils.ToolHelper
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 31 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at slimeknights.harvesttweaks.ExtraHarvestLevelHandler.breakSpeed(ExtraHarvestLevelHandler.java:46)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_41_ExtraHarvestLevelHandler_breakSpeed_BreakSpeed.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.event.ForgeEventFactory.getBreakSpeed(ForgeEventFactory.java:171)
	at net.minecraft.entity.player.EntityPlayer.getDigSpeed(EntityPlayer.java:836)
	at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:234)
	at net.minecraft.block.Block.func_180647_a(Block.java:559)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185903_a(BlockStateContainer.java:408)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:246)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1516)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2247)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['pap1723'/299, l='MpServer', x=-34.34, y=66.00, z=256.80]]
	Chunk stats: MultiplayerChunkCache: 521, 521
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-36,64,256), Chunk: (at 12,4,0 in -3,16; contains blocks -48,0,256 to -33,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3014 game time, 3014 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 75 total; [EntitySkeleton['Skeleton'/137, l='MpServer', x=-15.71, y=35.00, z=190.49], EntitySpider['Spider'/138, l='MpServer', x=-24.06, y=56.00, z=178.00], EntitySheep['Sheep'/139, l='MpServer', x=-23.16, y=66.00, z=214.56], EntitySheep['Sheep'/140, l='MpServer', x=-29.27, y=67.00, z=215.51], EntityZombie['Zombie'/141, l='MpServer', x=-23.50, y=31.00, z=227.50], EntityCreeper['Creeper'/142, l='MpServer', x=-22.50, y=31.00, z=226.50], EntityCreeper['Creeper'/143, l='MpServer', x=-22.22, y=31.00, z=224.46], EntityBat['Bat'/144, l='MpServer', x=-32.20, y=21.46, z=229.79], EntitySheep['Sheep'/145, l='MpServer', x=-27.27, y=68.00, z=224.49], EntityCreeper['Creeper'/146, l='MpServer', x=-25.50, y=50.00, z=323.50], EntityCreeper['Creeper'/147, l='MpServer', x=-22.50, y=50.00, z=328.50], EntitySpider['Spider'/148, l='MpServer', x=-27.01, y=50.00, z=325.99], EntitySkeleton['Skeleton'/168, l='MpServer', x=-17.59, y=34.00, z=189.49], EntitySheep['Sheep'/169, l='MpServer', x=-13.50, y=66.00, z=204.73], EntitySheep['Sheep'/170, l='MpServer', x=-5.50, y=69.00, z=240.81], EntitySheep['Sheep'/171, l='MpServer', x=-14.18, y=64.00, z=266.39], EntitySheep['Sheep'/172, l='MpServer', x=-0.74, y=64.00, z=271.36], EntitySheep['Sheep'/173, l='MpServer', x=-2.27, y=64.00, z=272.04], EntityCreeper['Creeper'/174, l='MpServer', x=-11.40, y=28.00, z=326.15], EntityBat['Bat'/47, l='MpServer', x=-103.01, y=38.74, z=236.14], EntityCreeper['Creeper'/175, l='MpServer', x=-1.42, y=28.00, z=335.83], EntitySkeleton['Skeleton'/48, l='MpServer', x=-99.51, y=25.00, z=286.78], EntityBat['Bat'/176, l='MpServer', x=-15.94, y=50.12, z=322.02], EntityBat['Bat'/304, l='MpServer', x=39.57, y=29.52, z=246.75], EntityCreeper['Creeper'/49, l='MpServer', x=-102.50, y=27.00, z=306.50], EntityPlayerSP['pap1723'/299, l='MpServer', x=-34.34, y=66.00, z=256.80], EntitySheep['Sheep'/50, l='MpServer', x=-104.27, y=72.00, z=322.58], EntityBat['Bat'/59, l='MpServer', x=-83.89, y=24.03, z=237.06], EntityCreeper['Creeper'/60, l='MpServer', x=-89.50, y=15.00, z=298.50], EntityWitch['Witch'/61, l='MpServer', x=-97.86, y=37.00, z=289.43], EntitySheep['Sheep'/62, l='MpServer', x=-94.42, y=72.00, z=326.98], EntityZombie['Zombie'/191, l='MpServer', x=12.73, y=30.00, z=179.44], EntitySheep['Sheep'/63, l='MpServer', x=-91.99, y=72.00, z=335.29], EntitySheep['Sheep'/192, l='MpServer', x=9.83, y=69.00, z=187.79], EntitySheep['Sheep'/64, l='MpServer', x=-93.55, y=72.00, z=327.19], EntitySheep['Sheep'/193, l='MpServer', x=14.19, y=66.00, z=205.38], EntitySheep['Sheep'/65, l='MpServer', x=-86.16, y=72.00, z=330.28], EntitySheep['Sheep'/194, l='MpServer', x=9.27, y=67.00, z=198.80], EntitySheep['Sheep'/66, l='MpServer', x=-94.25, y=72.00, z=325.64], EntitySheep['Sheep'/195, l='MpServer', x=2.78, y=67.00, z=197.52], EntityZombie['Zombie'/196, l='MpServer', x=1.50, y=41.00, z=218.50], EntityItem['item.tile.flower1.dandelion'/197, l='MpServer', x=4.48, y=68.00, z=231.52], EntityZombie['Zombie'/75, l='MpServer', x=-70.50, y=50.00, z=238.50], EntityZombie['Zombie'/76, l='MpServer', x=-66.50, y=28.00, z=246.50], EntityCreeper['Creeper'/77, l='MpServer', x=-71.22, y=52.00, z=282.50], EntitySheep['Sheep'/78, l='MpServer', x=-66.51, y=72.00, z=285.81], EntitySheep['Sheep'/79, l='MpServer', x=-62.13, y=70.00, z=293.47], EntitySheep['Sheep'/80, l='MpServer', x=-65.66, y=70.00, z=291.75], EntitySpider['Spider'/211, l='MpServer', x=28.01, y=48.00, z=209.00], EntitySquid['Squid'/212, l='MpServer', x=26.11, y=56.37, z=321.97], EntityChicken['Chicken'/215, l='MpServer', x=14.85, y=64.00, z=337.42], EntitySheep['Sheep'/90, l='MpServer', x=-52.04, y=68.00, z=186.49], EntityZombie['Zombie'/91, l='MpServer', x=-51.26, y=20.00, z=259.47], EntityCreeper['Creeper'/92, l='MpServer', x=-62.51, y=52.00, z=278.80], EntitySheep['Sheep'/220, l='MpServer', x=36.25, y=69.00, z=178.40], EntitySheep['Sheep'/93, l='MpServer', x=-58.11, y=70.00, z=297.58], EntitySkeleton['Skeleton'/94, l='MpServer', x=-49.90, y=48.00, z=306.41], EntityCreeper['Creeper'/222, l='MpServer', x=38.50, y=32.00, z=250.50], EntityBat['Bat'/95, l='MpServer', x=-48.94, y=39.93, z=322.78], EntitySkeleton['Skeleton'/223, l='MpServer', x=45.50, y=27.00, z=256.50], EntityZombie['Zombie'/224, l='MpServer', x=41.50, y=26.00, z=259.50], EntityBat['Bat'/225, l='MpServer', x=29.13, y=24.71, z=262.98], EntitySheep['Sheep'/104, l='MpServer', x=-47.06, y=67.00, z=186.45], EntitySheep['Sheep'/105, l='MpServer', x=-44.40, y=67.00, z=200.19], EntitySheep['Sheep'/106, l='MpServer', x=-39.22, y=68.00, z=189.71], EntitySkeleton['Skeleton'/107, l='MpServer', x=-45.50, y=13.00, z=210.50], EntityCreeper['Creeper'/108, l='MpServer', x=-43.82, y=31.00, z=236.58], EntityBat['Bat'/109, l='MpServer', x=-28.62, y=19.31, z=229.43], EntityZombie['Zombie'/110, l='MpServer', x=-44.50, y=30.00, z=252.50], EntityCreeper['Creeper'/111, l='MpServer', x=-45.55, y=31.00, z=272.78], EntitySkeleton['Skeleton'/112, l='MpServer', x=-42.47, y=52.00, z=311.29], EntityCreeper['Creeper'/113, l='MpServer', x=-34.23, y=50.00, z=312.47], EntitySkeleton['Skeleton'/114, l='MpServer', x=-39.50, y=42.00, z=329.67], EntityBat['Bat'/115, l='MpServer', x=-33.25, y=50.10, z=331.75], EntityItem['item.tile.stonebrick'/380, l='MpServer', x=-35.09, y=66.00, z=255.31]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_162, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5913505296 bytes (5639 MB) / 7392460800 bytes (7050 MB) up to 9320792064 bytes (8889 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms6000m -Xmx10000m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.2.2624 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID              | Version                | Source                                  | Signature                                |
	|:--------- |:--------------- |:---------------------- |:--------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft       | 1.12.2                 | minecraft.jar                           | None                                     |
	| UCHIJAAAA | mcp             | 9.42                   | minecraft.jar                           | None                                     |
	| UCHIJAAAA | FML             | 8.0.99.99              | forge-1.12.2-14.23.2.2624-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge           | 14.23.2.2624           | forge-1.12.2-14.23.2.2624-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | crafttweaker    | 4.1.5                  | CraftTweaker2-1.12-4.1.5.jar            | None                                     |
	| UCHIJAAAA | ctgui           | 1.0.0                  | CraftTweaker2-1.12-4.1.5.jar            | None                                     |
	| UCHIJAAAA | jei             | 4.8.5.147              | jei_1.12.2-4.8.5.147.jar                | None                                     |
	| UCHIJAAAA | crafttweakerjei | 2.0.0                  | CraftTweaker2-1.12-4.1.5.jar            | None                                     |
	| UCHIJAAAA | cucumber        | 1.0.4                  | cucumber-1.12-1.0.4.jar                 | None                                     |
	| UCHIJAAAA | mantle          | 1.12-1.3.1.21          | Mantle-1.12-1.3.1.21.jar                | None                                     |
	| UCHIJAAAA | worldstripper   | 1.5.1-1.12.2           | World-Stripper-1.5.1-1.12.2.jar         | None                                     |
	| UCHIJAAAA | harvesttweaks   | 1.12-0.1.5.DEV.86c8a67 | HarvestTweaks-1.12-0.1.5.jar            | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13506 Compatibility Profile Context 23.20.15002.11' Renderer: 'AMD Radeon R9 200 Series'
	Pulsar/harvesttweaks loaded Pulses: 
		- blocks (Enabled/Forced)
		- items (Enabled/Forced)

	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: AMD Radeon R9 200 Series GL version 4.5.13506 Compatibility Profile Context 23.20.15002.11, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz`

**Comment by bonii-xx** [comment]
Use https://minecraft.curseforge.com/projects/harvest-tweaks/files/2507444
